### ISSUE TITLE
Tips on Android emulator setup

### ISSUE THREAD

**Issue by d0lph1n98** [idanr1986/cuckoo-droid#15]
Based on this [reference](http://padfoot999.proboards.com/thread/184/setting-cuckoodroid). I've managed to do until xposed apk installation but the changes need to be applied by rebooting and the emulator stuck like forever without even shutting down. So how did you guys managed to do that part?

![sample](http://i.imgur.com/hk4ene3.png)

**Comment by idanr1986** [comment]
in the new emulator you need to copy the system.img from android-sdk-linux/system-images/android-16/google_apis/arm to the avd folder and this will keep all changes to the system partition persistent 
good reference : https://justus.berlin/2015/02/make-persistent-changes-to-system-in-android-emulator/
