### ISSUE TITLE
android x86 issues!!!!!!!!

### ISSUE THREAD

**Issue by blackorbird** [idanr1986/cuckoo-droid#25]
Browser can access the Internet，but app can't !!!
i use the x86 4.4 ,tell me how to analy the internet data for app

**Comment by DuyThangDecima** [comment]
@shiyelin  I have same problem. how to solve this issue???

**Comment by DuyThangDecima** [comment]
I finded my issue, Browser can access the Internet but app can't connect network , because app check card wifi, mobile network not found.
Slove:
I install Xpose app and moudule fake wifi, 
https://github.com/lemonsqueeze/fakewificonnection
