### ISSUE TITLE
droidmon not working

### ISSUE THREAD

**Issue by cuckoooo** [idanr1986/cuckoo-droid#3]
droimon not working in cuckoodroid due to error (droidmon error:/data/local/tmp/hooks.json:open failed:ENOENT(No such file or directory)

**Comment by idanr1986** [comment]
with witch emulation type you are using?

**Comment by cuckoooo** [comment]
I am using configuration setup 2(Preparing the Guest (Android Emulator)) and setup 3(Preparing the Guest (Android Device Cross-platform))

**Comment by cuckoooo** [comment]
and emulation type gpu off in setup 2,and snapshot in setup3.

**Comment by idanr1986** [comment]
you should put the file hooks.json in /data/local/tmp/hooks.json
https://github.com/idanr1986/droidmon
