### ISSUE TITLE
Please fix instructions in README

### ISSUE THREAD

**Issue by JoyMitra** [idanr1986/cuckoo-droid#31]
git pull from droid results in merge conflict due to unrelated histories between cuckoo and cuckooDroid. Please fix the git pull command to the following and it will work.

git pull --no-edit --allow-unrelated-histories -s recursive -X theirs droid master

**Comment by lovina37** [comment]
@JoyMitra  can you tell mew if cuckoodroid works perfectly fine with you ??

**Comment by idanr1986** [comment]
done
