### ISSUE TITLE
Two Problems:lack of modules and sdk version

### ISSUE THREAD

**Issue by Zhang343750200** [idanr1986/cuckoo-droid#32]
I'v got two problems:
1. Error:  [root] CRITICAL: CuckooCriticalError: Unable to import plugin "modules.processing.apkinfo": No module named androguard.core.analysis.analysis
sorry,I didn't find this module in the project folder, what should I do?
2.*************************************************************************
The "android" command is deprecated.
For manual SDK, AVD, and project management, please use Android Studio.
For command-line tools, use tools/bin/sdkmanager and tools/bin/avdmanager
*************************************************************************
so, what sdk version I should use? I wish you could give me a suggestion.
Thank you!

**Comment by idanr1986** [comment]
Pip install androguard

**Comment by Zhang343750200** [comment]
Another question hope to answer :  Can cuckoo work well with MacOSX?

**Comment by idanr1986** [comment]
Yes I actually work with cuckoodroid  on a mac

**Comment by Zhang343750200** [comment]
What's your sdk version? I use the latest sdk version, but when I follow your instructions with command line "android avd", the command has been  deprecated. Does the version of sdk affects the running on cuckoo?
