### ISSUE TITLE
No Dynamic Analysis Results [Cuckoodroid]

### ISSUE THREAD

**Issue by krishnadev6** [idanr1986/cuckoo-droid#60]
@idanr1986 @jbremer 
I am using Cuckoodroid with Android x86 ISO on Virtualbox. 
I am able to get the static analysis of all APK files. 
But even though the apk files runs in VM i am not getting any data on dynamic Analysis on report. 
The working window shows like this : 

![screenshot from 2018-02-09 19-10-50](https://user-images.githubusercontent.com/15974603/36030590-db07a3c8-0dcd-11e8-8f3c-181f6dfd9ac6.png)

`

```
> /usr/local/lib/python2.7/dist-packages/sqlalchemy/sql/compiler.py:572: SAWarning: Can't resolve label reference 'added_on desc'; converting to text() (this warning may be suppressed after 10 occurrences)
>   util.ellipses_string(element.element))
> 2018-02-09 18:53:07,828 [lib.cuckoo.core.scheduler] INFO: Using "virtualbox" machine manager
> 2018-02-09 18:53:08,584 [lib.cuckoo.core.scheduler] INFO: Loaded 1 machine/s
> 2018-02-09 18:53:08,593 [lib.cuckoo.core.scheduler] INFO: Waiting for analysis tasks.
> /usr/local/lib/python2.7/dist-packages/sqlalchemy/sql/compiler.py:572: SAWarning: Can't resolve label reference 'priority desc, added_on'; converting to text() (this warning may be suppressed after 10 occurrences)
>   util.ellipses_string(element.element))
> 2018-02-09 18:53:43,300 [lib.cuckoo.core.scheduler] INFO: Starting analysis of FILE "/tmp/cuckoo-tmp/upload_8WoKEp/Virus2 Cleaner Antivirus Booster MAX Security_v1.4.9_apkpure.com.apk" (task=4)
> 2018-02-09 18:53:43,651 [lib.cuckoo.core.scheduler] INFO: Task #4: acquired machine android1 (label=android1)
> 2018-02-09 18:53:43,662 [modules.auxiliary.sniffer] INFO: Started sniffer with PID 18311 (interface=vboxnet0, host=192.168.56.101, dump path=/home/kichu/111/cuckoo/storage/analyses/4/dump.pcap)
> 2018-02-09 18:53:47,370 [lib.cuckoo.core.guest] INFO: Starting analysis on guest (id=android1, ip=192.168.56.101)
> 2018-02-09 18:56:01,639 [lib.cuckoo.core.guest] INFO: android1: analysis completed successfully
> 2018-02-09 18:56:01,707 [modules.machinery.virtualbox] INFO: Successfully generated memory dump for virtual machine with label android1 to path /home/kichu/111/cuckoo/storage/analyses/4/memory.dmp
> 2018-02-09 18:56:06,930 [modules.processing.apkinfo] WARNING: Dex size bigger than: None
> 2018-02-09 18:56:06,945 [modules.processing.memory] ERROR: Cannot run volatility module: volatility library not available
> 2018-02-09 18:56:07,571 [lib.cuckoo.common.objects] WARNING: Unable to import pydeep (install with `pip install pydeep`)
> 2018-02-09 18:56:10,888 [lib.cuckoo.core.plugins] ERROR: Failed to run the reporting module "MongoDB":
> Traceback (most recent call last):
>   File "/home/kichu/111/cuckoo/lib/cuckoo/core/plugins.py", line 505, in process
>     current.run(self.results)
>   File "/home/kichu/111/cuckoo/modules/reporting/mongodb.py", line 216, in run
>     self.conn.disconnect()
>   File "/usr/local/lib/python2.7/dist-packages/pymongo/database.py", line 1053, in __call__
>     self.__name, self.__client.__class__.__name__))
> TypeError: 'Database' object is not callable. If you meant to call the 'disconnect' method on a 'MongoClient' object it is failing because no such method exists.
> 2018-02-09 18:56:11,258 [lib.cuckoo.core.scheduler] INFO: Task #4: reports generation completed (path=/home/kichu/111/cuckoo/storage/analyses/4)
> 2018-02-09 18:56:11,324 [lib.cuckoo.core.scheduler] INFO: Task #4: analysis procedure completed
```

`

**Comment by seantree** [comment]
Is your guest machine configured properly?

**Comment by krishnadev6** [comment]
@seantree yes Analysis is running but in report dynamic analysis seems empty.

**Comment by wickywaka** [comment]
I had faced kind of several situation, the problem in my case was that the Droidmon processing module wasn't reading the JSON data properly. More specifically here: https://github.com/idanr1986/cuckoo-droid/blob/1350274639473d3d2b0ac740cae133ca53ab7444/modules/processing/droidmon.py#L399

Here it tries to load the line directly but in my case there was date and time info at the start of the line and after that the rest of the string was valid JSON. What I had to do was remove the date and time part of the string before the above mentioned line.

You can print the line there to see if its valid json. I am not sure if you have the same problem, try running the cuckoo.py with -d parameter to see debug messages. It will give you more idea of whats going on.

**Comment by Eterna1** [comment]
@krishnadev6 There isn't much information in the log you provided.
Some ideas about how to troubleshot the problem:

- What files do you have in folder /home/kichu/111/cuckoo/storage/analyses/4/logs and what is their content?

- Does you virtual machine starts at all?

- If yes. You can enter the virtual machine when the analalysis is ongoing (by pressing "Show") and check if the android emulator is running. You can check using `adb logcat` whether droidmon runs properly (droidmon writes many data to logcat). When you entered virtual machine you can check what agent.py writes on the terminal

**Comment by krishnadev6** [comment]
@Eterna1 I am using Android X86 ISO in Virtual Box.
Yes the VM starts and the application gets installed and it opens. 

After a specific time it closes and shows analysis is completed. Only static analysis report is generated. 

Logs Folder has 2 files Droidmon log and Droidmon Error log both are blank.

**Comment by wickywaka** [comment]
Check if droidmon is printing something to logcat. As @Eterna1 said, check if droidmon is printing something to logcat.
It will also show if droidmon is having some errors.

**Comment by wickywaka** [comment]
I faced the same problem once and the reason was that droidmon wasn't able to read the hooks.json. I checked the logcat and driodmon was throwing error there that its unable to read hooks.json.

**Comment by seantree** [comment]
@krishnadev6 which version of cuckoo are you using? can you please share you VM guest machine by google drive I will check it with my setup.

**Comment by krishnadev6** [comment]
@seantree

**Comment by wickywaka** [comment]
@krishnadev6 Any updates?

**Comment by krishnadev6** [comment]
Thanks everyone! It is working now the problem was with droidmon. 
I checked dridmon error log and found that nothing is written on it. 

I am using Androidx86 Virtualbox iso. After configuring VM I run the create android emulator on guest device script for VM.  The script will only install Droidmon APK file into VM. But we also need to configure hooks for droidmon. but that is missing in the script. So I manually pushed the files to VM and its working now..

**Comment by seantree** [comment]
Hi @krishnadev6 Can you please mentioned the steps how did you solved the problem because I am also facing the similar problems and in my case my logs folders are empty.
waiting for positive reply

**Comment by krishnadev6** [comment]
Hi @seantree Sure!
The error for me was the droidmon was not installed the VM.
Steps to resolve : 
Go to utils folder under cuckoo directory -> Inside that there is a python script generate_hook_json.py->Eun the script. A new hooks.json file will be created. Then push the file to device via ADB.

Hope this will help.

**Comment by seantree** [comment]
Hi Thanks for the reply, I already followed those steps after that I pushed that file.

**Comment by krishnadev6** [comment]
@seantree 
Can you check whether you are getting IP inside the VM?

**Comment by seantree** [comment]
yes I am getting

**Comment by anhkhoa14592** [comment]
Hi all,

I've followed the @krishnadev6's instructions and fixed the problem but i think it's will helpful for another one meeting this situation if we can detail the way to solve:

**My enviroment:**
1. Host Machine on Vmware (XUbuntu 14.04 OS)
2. Guest Machine on Virtualbox (in Vmware): Android x84 4.4 RC2

**Ways to solve the problem**
1, come to cuckoo/utils/hooks_generator
2. Run generate_hook_json.py with `python generate_hook_json.py`. It will create hook.json in the same folder.
3. Using adb to push hook.json into **/data/local/tmp/hook.json** on Guest Machine (You must be root) by running `adb push hook.js  /data/local/tmp`
4. Finish

**Comment by code-error** [comment]
@krishnadev6 can you please share how you exactly configured cuckoodroid and android x86. I followed cuckoodroid official docs and failed miserably. It will be helpful.

**Comment by Adzeezul** [comment]
> I had faced kind of several situation, the problem in my case was that the Droidmon processing module wasn't reading the JSON data properly. More specifically here:
> 
> https://github.com/idanr1986/cuckoo-droid/blob/1350274639473d3d2b0ac740cae133ca53ab7444/modules/processing/droidmon.py#L399
> 
> Here it tries to load the line directly but in my case there was date and time info at the start of the line and after that the rest of the string was valid JSON. What I had to do was remove the date and time part of the string before the above mentioned line.
> 
> You can print the line there to see if its valid json. I am not sure if you have the same problem, try running the cuckoo.py with -d parameter to see debug messages. It will give you more idea of whats going on.

How exactly you do this? I need an explanation on it.

**Comment by wickywaka** [comment]
> > I had faced kind of several situation, the problem in my case was that the Droidmon processing module wasn't reading the JSON data properly. More specifically here:
> > https://github.com/idanr1986/cuckoo-droid/blob/1350274639473d3d2b0ac740cae133ca53ab7444/modules/processing/droidmon.py#L399
> > 
> > Here it tries to load the line directly but in my case there was date and time info at the start of the line and after that the rest of the string was valid JSON. What I had to do was remove the date and time part of the string before the above mentioned line.
> > You can print the line there to see if its valid json. I am not sure if you have the same problem, try running the cuckoo.py with -d parameter to see debug messages. It will give you more idea of whats going on.
> 
> How exactly you do this? I need an explanation on it.

Well that was more than 4 years ago so don't remember exactly. My wild guess would be using a `print` statement or something similar.
