### ISSUE TITLE
start function raised an error: BAD_APK

### ISSUE THREAD

**Issue by Eterna1** [idanr1986/cuckoo-droid#61]
Hello. I am trying to set up sandbox using method "Preparing the Guest (Android on Linux Machine)" this time. I am using cuckoo 1.2 for this because the new version of cuckoo was hanging up. I get this error: 

ERROR: Analysis failed: The package "modules.packages.apk" start function raised an error: BAD_APK:baba.apk

Does anyone know how to solve this issue?

**Comment by wickywaka** [comment]
Is it a valid APK file?
Can you just test it using androguard to see if its detecting it as valid of invalid?

**Comment by Eterna1** [comment]
yes. It is a valid APK file, although I get following error when running androguard:

```
a@x ~/Desktop/op_baba $ androlyze.py -s
Androguard version 3.1.0
In [1]: AnalyzeAPK("baba.apk")
No handlers could be found for logger "androguard.axml"
---------------------------------------------------------------------------
UnicodeEncodeError                        Traceback (most recent call last)
[.....]
```
But it doesn't matter because any APK doesn't work.

**Comment by wickywaka** [comment]
I never managed to make it work using your method, I am using it with "Preparing the Guest (Android Emulator)" method.

How did you made the emulator work inside the VirtualBox?  I couldn't even start it inside the virutalbox.

**Comment by Eterna1** [comment]
> How did you made the emulator work inside the VirtualBox? I couldn't even start it inside the virutalbox.

I've switched off GPU emulation option and use some new Linux distribution. Documentation says to use some very old version of Ubuntu

**Comment by wickywaka** [comment]
Try using "get_package_activity_name" inside the apk package instead of the one that uses androgaurd to get package name.. May be that will work.

**Comment by Eterna1** [comment]
I reverse-engineered the problem a little bit. In file `analyzer/android_on_linux/lib/api/androguard` in class `APK` in function `__init__` the following code crashes on function open() because there is no file filename in the guest machine :

```python
        if raw == True:
            self.__raw = filename
        else:
            fd = open(filename, "rb")
            self.__raw = fd.read()
            fd.close()
```

**Comment by Eterna1** [comment]
ok. I've solved this issue.
I added following code before `open`:

```python
    import os
    os.system("cp /data/local"+filename+" "+filename)
```

Maybe the thing is that my guest machine runs as root.

Now, I get another errors....

**Comment by wickywaka** [comment]
Try replacing `get_package_activity_name` by `get_package_activity_name_old` in https://github.com/idanr1986/cuckoo-droid/blob/1350274639473d3d2b0ac740cae133ca53ab7444/analyzer/android_on_linux/modules/packages/apk.py#L29

What are the other errors?

**Comment by Eterna1** [comment]
The sandbox works now for most APKs, but one APK doesn't work. The error is `Error: Analysis failed: The package "modules.packages.apk" start function raised an error: INVALID_APK:baba.apk`. This apk works in my other cuckoodroid configuration (emulator on Host machine with cuckoo 2.x).

> Try replacing get_package_activity_name by get_package_activity_name_old

after changing this I get following error:
`Error: Analysis failed: The package "modules.packages.apk" start function raised an error: failed to get package and main activity from sample!`

The sample is [here](https://koodous.com/apks/98575f33ebf641f1f32c5cf238f4925d86d2447e9e2d30c84e72fafe74050a65). I think that also other people will have problems wit this sample
I will be working on this.

//EDIT

I've solved this issue, here is the solution:

- following diff:
```
--- a/analyzer/android_on_linux/lib/api/adb.py
+++ b/analyzer/android_on_linux/lib/api/adb.py
@@ -150,10 +150,10 @@ def dump_droidmon_logs(package):
         apimonitor = ""
         shell = ""
         for line in log_file:
-            if tag in line:
+            if tag in line.encode("string_escape"):
                 out = re.sub(tag+":", "", line)
                 apimonitor=apimonitor+out
-            if tag_error in line:
+            if tag_error in line.encode("string_escape"):
                 out = re.sub(tag_error+":", "", line)
                 shell=shell+out
         utils.send_file("logs/droidmon.log",apimonitor)
```

- replaced classes `AXMLParser` and `AXMLPrinter` from the new version of androguard to the local version of androguard
- copied file public.py from new version of androguard to `analyzer/android_on_linux/lib/api/androguard/public.py` and imported this file
- patched androguard installed globally on the system in file `bytecodes.apk.py`.
I changed line `l.append( str( value ) )` to `l.append( str( value.encode('utf-8') ) )`

**Comment by wickywaka** [comment]
Did you use  [Cuckoodroid 2.0](https://github.com/idanr1986/cuckoodroid-2.0) for configuring with cuckoo 2.0? I am still using cuckoo 1.2.

**Comment by Eterna1** [comment]
> Did you use Cuckoodroid 2.0 for configuring with cuckoo 2.0? I am still using cuckoo 1.2.

I looked at cuckoodroid 2.0, crated an issue, no solution.
I don't think It works.

**Comment by SAUMYA1995-dev** [comment]
2020-05-05 12:32:21,572 [lib.cuckoo.core.scheduler] INFO: Waiting for analysis tasks.
2020-05-05 12:32:22,583 [lib.cuckoo.core.database] DEBUG: Database error fetching task: Can't resolve label reference for ORDER BY / GROUP BY. Textual SQL expression 'priority desc, added_on' should be explicitly declared as text('priority desc, added_on')
2020-05-05 12:32:23,594 [lib.cuckoo.core.database] DEBUG: Database error fetching task: Can't resolve label reference for ORDER BY / GROUP BY. Textual SQL expression 'priority desc, added_on' should be explicitly declared as text('priority desc, added_on')
2020-05-05 12:32:24,605 [lib.cuckoo.core.database] DEBUG: Database error fetching task: Can't resolve label reference for ORDER BY / GROUP BY. Textual SQL expression 'priority desc, added_on' should be explicitly declared as text('priority desc, added_on')






can anybody help me with this???
