### ISSUE TITLE
please try upgrading to the latest version of agent.py (>= 0.8)

### ISSUE THREAD

**Issue by happyhq** [idanr1986/cuckoo-droid#63]
when I  submit a android  task for  cuckoo .It says:
2018-02-25 00:27:52,063 [cuckoo.core.scheduler] ERROR: Error from the Cuckoo Guest: Cuckoo Agent failed without error status, please try upgrading to the latest version of agent.py (>= 0.8) and notify us if the issue persists.  
But I can't find  agent.py (>= 0.8)  .How can i do??
![bf686582-68db-489d-ad01-c8de6eac110b](https://user-images.githubusercontent.com/6745870/36639649-380f0d10-1a4c-11e8-83e0-547d7f0527ff.png)
![Uploading BF686582-68DB-489D-AD01-C8DE6EAC110B.png…]()

**Comment by wickywaka** [comment]
Which version of cuckoo is it?

**Comment by happyhq** [comment]
Cuckoo version: 2.0.5
OS version: posix
OS release: Ubuntu 14.04 trusty
Python version: 2.7.6
Python implementation: CPython
Machine arch: x86_64
@waqarrashid33

**Comment by happyhq** [comment]
Now  .I change Cuckoo Host version to   V1.2.It`s that right version for android ? @waqarrashid33

**Comment by wickywaka** [comment]
Yes. It won't work with latest cuckoo.
Did you made it work with V 1.2?

**Comment by happyhq** [comment]
yes.It's my fault.
I  update the system  from  ubuntu12.04 to 14.04. Then the problem happen.
But now  i  reload the system  from 14.04.The problem  won't happen  again.
Thanks!
