### ISSUE TITLE
No Android Dynamic Analysis and Analysis.log

### ISSUE THREAD

**Issue by nothing0126** [idanr1986/cuckoo-droid#78]
Hi everyone!
Note: I ran on Mac OS
I have some questions:
 1. File Analysis.log is resuilt from  Android Dynamic Analysis?
 2. I analyzed a file apk,but no file Analysis.log and Android Dynamic Analysis in report.html 
 3. I submited 01 file apk but have 02 ID, the apk is facebook.apk, but what is .DS_Store??
 `Success: File "/Users/imac/Desktop/cuckooDroid/test/.DS_Store" added as task with ID 1
 Success: File "/Users/imac/Desktop/cuckooDroid/test/facebook.apk" added as task with ID 2`

**Comment by wickywaka** [comment]
run it -d and paste the output here.

**Comment by DucTrungNguyen** [comment]
@waqarrashid33 I don't really understand your suggest. 
This is my command I have run:
`python cuckoo.py -d`
So, your mean is
`python cuckoo.py -d <path output>`?
I will try this command.
Thank for your support

**Comment by nothing0126** [comment]
this is ERROR when I analysis
`2018-10-04 12:55:37,535 [lib.cuckoo.core.scheduler] ERROR: aosx_1: unable to upload malware to analysis machine: [Errno 32] Broken pipe`

**Comment by wickywaka** [comment]
It seems the apk file is too big. Cuckoodroid can only analyze files upto
10MB. Did you tried another smaller apk file?

Nguyễn Đức Trung <notifications@github.com> schrieb am Do., 4. Okt. 2018,
08:04:

**Comment by nothing0126** [comment]
@waqarrashid33 
Thank for your suggested about files under 10MB.
I have tried with file under 10MB and it ran but input had only one file .apk and when i submitted, it was added  to 2 ID : ./DS_Store and test.apk as follow:
`Success: File "/Users/imac/Desktop/cuckooDroid/test/.DS_Store" added as task with ID 1 
Success: File "/Users/imac/Desktop/cuckooDroid/test/test.apk" added as task with ID 2` 
I think only ID can add is apk.test
So is there any solution to solve this problem?

**Comment by arabin-android** [comment]
Need help with this issue. i did everything as per document but getting this error please help me.

arabin@arabin-Mac:~/analysis/cuckoo/utils/android_emulator_creator$ ./create_guest_avd.sh
adb has been found.
Pushing /system/xbin/su binary
./create_guest_avd.sh: line 19: remount: command not found
./create_guest_avd.sh: line 20: push: command not found
./create_guest_avd.sh: line 21: shell: command not found
Installing application Superuser
install: missing destination file operand after 'apps/Superuser.apk'
Try 'install --help' for more information.
Installing Xposed Application
install: missing destination file operand after 'apps/de.robv.android.xposed.installer_v33_36570c.apk'
Try 'install --help' for more information.
Installing Droidmon Application
install: missing destination file operand after 'hooking/Droidmon.apk'
Try 'install --help' for more information.
Installing Anti Emulator Detection Application
install: missing destination file operand after 'hooking/EmulatorAntiDetect.apk'
Try 'install --help' for more information.
./create_guest_avd.sh: line 37: push: command not found
./create_guest_avd.sh: line 38: push: command not found
./create_guest_avd.sh: line 39: push: command not found
Installing Content Generator
install: missing destination file operand after 'apps/ImportContacts.apk'
Try 'install --help' for more information.
Installing Cuckoo Agent and Python for ARM
./create_guest_avd.sh: line 47: push: command not found
./create_guest_avd.sh: line 48: shell: command not found
./create_guest_avd.sh: line 49: shell: command not found
./create_guest_avd.sh: line 50: shell: command not found
Device is ready!

**Comment by nothing0126** [comment]
@arabin-android 
Have you watched this tutorials: [https://www.youtube.com/watch?v=mUoz71KfwLg&list=PLWHO6M8IznQBPzRlcrZ99LG0n4bktm0x8](url)
I suggest you to config a new AVD.
 MAC os seem ubuntu.

**Comment by arabin-android** [comment]
Thanks @DucTrungNguyen but the link you have given above is not working. can you tell how did you run CuckooDorid in MacOS i am using macOS highsierra. But for cuckoo droid i installed ubuntu as a dual bot.

**Comment by nothing0126** [comment]
Have three installaion with cuckooDroid. I have choosed _Preparing the Guest (Android Emulator)_ and configed it like this tutorials.
I'm using MAC os too.
Readmore: [https://cuckoo-droid.readthedocs.io/en/latest/installation/guest_android_avd/](url)
Good luck to you!

**Comment by wickywaka** [comment]
#81

**Comment by SAUMYA1995-dev** [comment]
> Hi everyone!
> Note: I ran on Mac OS
> I have some questions:
> 
>     1. File Analysis.log is resuilt from  Android Dynamic Analysis?
> 
>     2. I analyzed a file apk,but no file Analysis.log and Android Dynamic Analysis in report.html
> 
>     3. I submited 01 file apk but have 02 ID, the apk is facebook.apk, but what is .DS_Store??
>        `Success: File "/Users/imac/Desktop/cuckooDroid/test/.DS_Store" added as task with ID 1  Success: File "/Users/imac/Desktop/cuckooDroid/test/facebook.apk" added as task with ID 2`

how did you solve this ???
