### ISSUE TITLE
how can I get api

### ISSUE THREAD

**Issue by dinasaif** [idanr1986/cuckoo-droid#8]
I want to make analysis for android apk and I want to get all api from apk 
1-How can I get them with cuckoo please explain that in details?
2-Is cuckoo static analysis only or dynamic also?
Thanks for your help

**Comment by idanr1986** [comment]
Your question is unclear when you say get all the api , you mean hook all the methods or decompiling the application?

**Comment by dinasaif** [comment]
I mean get all methods please answer me with details because I'm new in this field

**Comment by idanr1986** [comment]
You question still unclear please send me private email explaining what are you trying to do.

Idanr1986@gmail.com
