### ISSUE TITLE
Unable to import plugin "modules.processing.googleplay": No module named requests

### ISSUE THREAD

**Issue by ReDistant** [idanr1986/cuckoo-droid#84]
Hey ,guys 
when i use the command 'python cuckoo.py -d ' , it output a problem with "CuckooCriticalError: Unable to import plugin "modules.processing.googleplay": No module named requests"
i sure the conf/processing.conf googleplay is off 
[googleplay]
enabled = no
android_id =
google_login =
google_password =
so what can i do for this problem ? i need your help , thx

**Comment by Felixho19** [comment]
`pip install requests`

**Comment by ReDistant** [comment]
> `pip install requests`
Thank you
